# #####################################################################
# Automatically generated by qmake (2.01a) Tue Dec 22 13:58:49 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += report.h \
    Card.h \
    flashcard.h
FORMS += report.ui \
    flashcard.ui
SOURCES += report.cpp \
    Card.cpp \
    flashcard.cpp \
    main.cpp
RESOURCES = flashcard.qrc
